POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Basics of Node.js",
    "author": "FS-Team",
    "url": "https://fullstackopen.com",
    "userId": "5fa869de06e5a828c085461b",
    "likes": 250
}